pipeline {
    agent any

    environment {
        REGISTRY_HOST = 'localhost:5443' 
        DEPLOY_SERVER = "${env.DEPLOY_HOSTNAME ?: env.COMPUTERNAME ?: 'host.docker.internal'}"
        REGISTRY_URL = "${REGISTRY_HOST}" 
        IMAGE_NAME   = "cinebook"
        IMAGE_TAG    = "latest"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    sh 'ls -la'

                    sh 'ls -la Server'

                    sh """ 
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f Server/Dockerfile .
                    """
                }
            }
        }

        stage('Docker Tag and Push') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'docker-registry',
                    usernameVariable: 'REGISTRY_USER',
                    passwordVariable: 'REGISTRY_PASS'
                )]) {
                    script {
                        sh  "docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}"

                        sh "echo $REGISTRY_PASS | docker login ${REGISTRY_URL} -u $REGISTRY_USER --password-stdin"

                        sh "docker push ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}"
                    }
                }
            }
        }

        stage('Deploy to Server') {
            steps {
                script {
                    // kích hoạt ssh agent để truy vập server
                    sshagent(['ssh-credentials']) {
                        // copy env file lên server
                        sh """
                            scp -o StrictHostKeyChecking=no .env.production jenkins@${DEPLOY_SERVER}:C:/Users/jenkins/app.env
                        """

                        // lấy lại user/pass Docker để đang nhập trên server đích
                        withCredentials([usernamePassword(
                            credentialsId: 'docker-registry',
                            usernameVariable: 'REGISTRY_USER',
                            passwordVariable: 'REGISTRY_PASS'
                        )]) {
                            // thực hiện lệnh ssh với escape đúng các biến
                            sh """
                                ssh -o StrictHostKeyChecking=no jenkins@${DEPLOY_SERVER} << ENDSSH
                                    echo "Dang nhap Docker..."
                                    echo ${REGISTRY_PASS} | docker login ${REGISTRY_URL} -u ${REGISTRY_USER} --password-stdin
                                    
                                    echo "Pull image..."
                                    docker pull ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}
                                    
                                    echo "Restart container..."
                                    docker stop ${IMAGE_NAME} || true
                                    docker rm ${IMAGE_NAME} || true
                                    docker run -d --name ${IMAGE_NAME} -p 80:8080 --restart always \\
                                        --env-file C:/Users/jenkins/app.env \\
                                        ${REGISTRY_URL}/${IMAGE_NAME}:${IMAGE_TAG}
                
                                    echo "Deployment completed!"
ENDSSH
                            """
                        }
                    }
                }
            }
        }
    }
}